-- MySQL Script generated by MySQL Workbench
-- Sun 10 Sep 2023 11:52:45 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Nome` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consumo` (
  `idConsumo` INT NOT NULL,
  `ValorMensal` DOUBLE NULL,
  `ValorAnual` DOUBLE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idConsumo`),
  INDEX `fk_Consumo_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Consumo_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaCompras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaCompras` (
  `NomeLista` INT NOT NULL,
  `QuantidadeItens` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `ValorTotal` DOUBLE NULL,
  `Mercado` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`NomeLista`),
  INDEX `fk_ListaCompras_Cliente_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_ListaCompras_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `idItem` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Preço` DOUBLE NULL,
  `ListaCompras_NomeLista` INT NOT NULL,
  PRIMARY KEY (`idItem`, `ListaCompras_NomeLista`),
  INDEX `fk_Item_ListaCompras1_idx` (`ListaCompras_NomeLista` ASC),
  CONSTRAINT `fk_Item_ListaCompras1`
    FOREIGN KEY (`ListaCompras_NomeLista`)
    REFERENCES `mydb`.`ListaCompras` (`NomeLista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
